var M_folderOpen_title     = "Open the following folder.";
var M_runExe_title         = "This browser cannot launch the DICOM image viewer.\nRun the following.";
var M_drive_alert          = "Cannot acquire the drive name.";
var M_reportListShow_close = "Close";
var M_reportListExist      = "Yes";
var M_pageString           = "Page  ";
var M_callUsagePath        = "../../OTHER/VIEWER/USAGE_EN.HTM";
